name: Nexus Mods

on:
  push:
    tags:
    - 'v*.*.*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release'
        required: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    env:
      VERSION: ${{ inputs.tag || github.ref_name }}

    steps:
    - uses: actions/checkout@v1

    - name: Download the release asset
      run: |
        RELEASE_ASSET_NAME="ui-galaxy-sizes_${VERSION#v}.zip"
        wget "https://github.com/hmlendea/stellaris-ui-galaxy-sizes/releases/download/${VERSION}/${RELEASE_ASSET_NAME}" -O "release.zip"

    - name: Upload
      uses: Nexus-Mods/upload-action@v1.0.0-beta.10
      with:
        api_key: ${{ secrets.NEXUSMODS_API_KEY }}
        file_id: 922249
        filename: release.zip
        display_name: ui-galaxy-sizes.zip
        version: ${{env.VERSION}}
        description: "Changelog: https://github.com/hmlendea/stellaris-ui-galaxy-sizes/releases/${{env.VERSION}}"
        category: main
        archive_existing_version: true
        update_mod_version: true
