name: Steam Workshop

on:
  push:
    tags:
    - 'v*.*.*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Download the release asset
      run: |
        wget "https://github.com/hmlendea/stellaris-ui-galaxy-sizes/releases/download/${{github.ref_name}}/ui-galaxy-sizes_${GITHUB_REF:11}.zip" -O "release.zip"
        unzip "release.zip" -d "release/"

    - name: Upload
      uses: hmlendea/steam-workshop-update@latest
      with:
        appid: 281990
        itemid: 2047543230
        path: "release/"
        changenote: "[url=https://github.com/hmlendea/stellaris-ui-galaxy-sizes/releases/tag/${{github.ref_name}}]Version ${{github.ref_name}}[/url]"
      env:
        STEAM_USERNAME: ${{secrets.STEAM_USERNAME}}
        STEAM_PASSWORD: ${{secrets.STEAM_PASSWORD}}
        STEAM_2FASEED: ${{secrets.STEAM_2FA_SEED}}
