name: Steam Workshop

on:
  push:
    tags:
    - 'v*.*.*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Download the release asset
      run: |
        wget "https://github.com/hmlendea/ui-galaxy-sizes/releases/download/${{github.ref_name}}/ui-galaxy-sizes_${GITHUB_REF:11}.zip" -O "ui-galaxy-sizes.zip"
        unzip "ui-galaxy-sizes.zip" -d "ui-galaxy-sizes/"

    - name: Upload
      uses: Weilbyte/steam-workshop-upload@v1
      with:
        appid: 281990
        itemid: 2047543230
        path: "ui-galaxy-sizes/"
        changenote: "[url=https://github.com/hmlendea/ui-galaxy-sizes/releases/tag/${{github.ref_name}}]Version ${{github.ref_name}}[/url]"
      env:
        STEAM_USERNAME: ${{secrets.STEAM_USERNAME}}
        STEAM_PASSWORD: ${{secrets.STEAM_PASSWORD}}
        STEAM_TFASEED: ${{secrets.STEAM_2FA_SEED}}
